
-- 분기별 분야 이익률 (기준 - KRX_INDUSTRY_CODE / 4 자리)

WITH TB_LATEST_COMPNAY AS
(
SELECT * 
  FROM TB_COMPANY_AND_DEFFERED A JOIN 
      (SELECT STOCK_ID, MAX(STANDARD_DATE) AS STANDARD_DATE FROM TB_COMPANY_AND_DEFFERED GROUP BY STOCK_ID) B USING (STOCK_ID, STANDARD_DATE)
 WHERE CLOSED_YN = 'N'
       AND RIGHT(STOCK_ID, 1) = '0'
       AND SECURITY_SECTOR = 0
),
TB_STATISTICS_BASE AS
(
-- 결산월이 다른 애들은 제외한다.
SELECT A.STANDARD_DATE, ASSET_TOTAL, DEBT_TOTAL, CAPITAL, CAPITAL_TOTAL, SALES, OPERATION_PROFIT, NET_PROFIT, KOSPI_YN, KRX_INDUSTRY_CODE
FROM   tb_company_stat_refined A JOIN TB_LATEST_COMPNAY B USING (STOCK_ID)
WHERE  LEFT(RIGHT(A.STANDARD_DATE,4),2) IN ( '03', '06', '09' ,'12' )
)
SELECT * FROM 
TB_STATISTICS_BASE
